**Problem 1: Basic Array Element Comparisons**
--

In [183]:
import numpy as np
arr = np.array([2, 5, 8, 10, 3, 6, 7])

In [184]:
#check and print which elements of the array are even

evens = []

for i in range(len(arr)):
    if arr[i] % 2 == 0:
        evens.append(arr[i])
print(f"Elements that are even numbers: {evens}.")

Elements that are even numbers: [2, 8, 10, 6].


**Problem 2: Find Prime Array Elements**
--

Given a 1D NumPy integer array of arbitrary length, write a Python script that checks to see which elements are prime numbers, and builds a corresponding True/False array.

In [220]:
def is_prime(num):                                  # check if number is a prime number
    if num <= 1:
        return False
    if num == 2:
        return True
    for i in range(2, num):
        if (num % i) == 0:
            return False
        else:
            return True

def check_prime(array):                             # find prime numbers in an array
    nums_list = np.zeros(array.shape, dtype = bool) #create an empty array that default contains False
    for i in range(len(array)):
        if is_prime(array[i]) == True:
            nums_list[i] = True
    return print(nums_list)

In [221]:
test_array = np.array([2, 3, 5, 6, 7, 11, 12, 13])
check_prime(test_array)

[ True  True  True False  True  True False  True]


**Problem 3: Nested For Loops with 2D Arrays**
--

1. The Fibonacci sequence starting with 0 runs across the first row.
2. Fibonacci sequences run down each column starting with the number in the first row.

In [222]:
import numpy as np
n = 10
a = np.zeros((n,n), dtype=int)

In [223]:
for i in range(n):
    if i == 0:                                  # first row
        for j in range(n):
            if j == 0:
                a[i,j] = 0
            elif j == 1:
                a[i,j] = 1
            else:
                a[i,j] = a[i,j-1] + (a[i, j-2])
    elif i == 1:                                # second row
        for j in range(n):
            if j == 0:
                a[i,j] = 1
            elif j == 1:
                a[i,j] = 1
            else:
                a[i,j] = a[i,j-1] + (a[i, j-2])
    else:                                       # third row and on
        for j in range(n):
            a[i,j] = a[i-1,j] + a[i-2,j]

print(a)

[[   0    1    1    2    3    5    8   13   21   34]
 [   1    1    2    3    5    8   13   21   34   55]
 [   1    2    3    5    8   13   21   34   55   89]
 [   2    3    5    8   13   21   34   55   89  144]
 [   3    5    8   13   21   34   55   89  144  233]
 [   5    8   13   21   34   55   89  144  233  377]
 [   8   13   21   34   55   89  144  233  377  610]
 [  13   21   34   55   89  144  233  377  610  987]
 [  21   34   55   89  144  233  377  610  987 1597]
 [  34   55   89  144  233  377  610  987 1597 2584]]


**Problem 4: While Loop Within a For Loop**
--

Each array, starts at the first element and sums consecutive elements using a while loop until the sum is greater
than or equal to 50. The script should print the sum and the index where it stopped for each array.

In [224]:
arrays_list = [np.array([10, 20, 30, 40, 50]), np.array([5, 15, 25]), np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [230]:
for i in range(len(arrays_list)):                            # runs for the # of arrays in list
    for j in range(len(arrays_list[i])):                     # range is # of elements in each array
        index = 0
        total = 0
        while (index < len(arrays_list[i])) and total < 50:  # index < # of elements in each array
            total += arrays_list[i][index]
            index += 1                                       
    print(f"Array {i + 1}: Sum = {total}, Index stopped = {index}")


Array 1: Sum = 60, Index stopped = 3
Array 2: Sum = 45, Index stopped = 3
Array 3: Sum = 45, Index stopped = 9


**Problem 5: Logical Testing with NumPy**
--

In [231]:
data = np.array([[5, 8, 3], [7, 2, 9], [6, 4, 1]])

In [233]:
# identifies and prints the location (row and column) of all elements that are greater than 6.

for i in range(len(data)):
    for j in range(len(data[i])):
        if data[i][j] > 6:
            print(f"{data[i][j]} is at row {i}, column {j}.")     

8 is at row 0, column 1.
7 is at row 1, column 0.
9 is at row 1, column 2.
