**1. Array Creation:**
--

In [2]:
import numpy as np

In [3]:
#a) create a 1D array containing numbers from 0 to 9

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#b) create a 3x3 matrix with numbers from 1 to 9

matrix = np.array([arr[1:4], arr[4:7], arr[7:]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#c) generate a 1D array of 10 random integers between 50-100

rand_num1 = np.random.uniform(50, 100, size = [10,1])
print(rand_num1)

[[96.69512874]
 [87.63113061]
 [75.91221317]
 [85.42706179]
 [85.32714459]
 [89.53924201]
 [80.59498907]
 [61.54617921]
 [57.32722764]
 [50.0135143 ]]


In [6]:
#d)create a 3x4 matrix of random floating-point numbers between 0 and 1

rand_num2 = np.random.uniform(0, 1, size = [3,4])
print(rand_num2)

[[0.77562441 0.57476246 0.43089064 0.91948012]
 [0.93005778 0.93772704 0.89120995 0.37805591]
 [0.67431073 0.72109947 0.20121533 0.49362173]]


**2. Array Indexing**
--

In [7]:
#a) all even numbers from 1a array
even = arr[::2]
print(even)

[0 2 4 6 8]


In [8]:
#b) second row of 1b matrix
second_row = matrix[1]
print(second_row)

[4 5 6]


In [9]:
#c) element at the third row and second column from 1b matrix
element = matrix[2,1]
print(element)

8


In [75]:
#d) from 1d matrix, extract all elements greater than 0.5

greater = np.where((rand_num2 > 0.5))
print(rand_num2[greater])

[0.77562441 0.57476246 0.91948012 0.93005778 0.93772704 0.89120995
 0.67431073 0.72109947]


**3. Basic Math Operations:**
--

In [38]:
#a) two arrays A and B of shape (4,4) with random int between 1-10
#and compute sum and product

array_A = np.random.uniform(1, 10, size = [4,4])
array_B = np.random.uniform(1, 10, size = [4,4])

In [39]:
array_A + array_B

array([[ 9.97724866, 12.956702  ,  8.70759432, 16.18961483],
       [14.33298619,  9.19032439, 12.87394624, 10.38602564],
       [18.23553543, 13.30749747, 15.27731526, 18.07303648],
       [11.31749836,  3.59759601, 14.386025  ,  7.76802386]])

In [40]:
array_A * array_B

array([[24.30185417, 40.30895348, 15.94719033, 65.34807256],
       [50.64694812, 19.39862243, 36.93479264, 24.39513567],
       [82.82690853, 42.01129714, 58.33536214, 81.64608021],
       [22.92600286,  2.95764389, 50.06296648, 12.83990034]])

In [41]:
#b) multiply 1D array created in 1a by 5
arr * 5 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
#c) subtract the mean of 1D array in 1a from each of its elements
mean = np.mean(arr)

arr - mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

**4. Basic Statistical Calculations:**
--

In [45]:
#a) compute mean, median, and standard deviation of array from 1a
mean = np.mean(arr)
median = np.median(arr)
sd = np.std(arr)

print('The mean is:', mean)
print('The median is', median)
print('The standard deviation is', sd)

The mean is: 4.5
The median is 4.5
The standard deviation is 2.8722813232690143


In [46]:
#b) find the min and max values of 1D array in 1d
minimum = np.min(rand_num2)
maximum = np.max(rand_num2)

print('The minimum is:', minimum)
print('The maximum is', maximum)

The minimum is: 0.20121532760836092
The maximum is 0.9377270387781438


In [71]:
#c) find the position of the min and max values of 1D array in 1c
min_1 = np.min(rand_num1)
max_1 = np.max(rand_num1)

In [79]:
index_min = np.where(rand_num1 == min_1) #minimum value
print('The index of the minimum is:', index_min)

The index of the minimum is: (array([9]), array([0]))


In [81]:
index_max = np.where(rand_num1 == max_1) #maximum value
print('The index of the maxminum is:', index_max)

The index of the maxminum is: (array([0]), array([0]))
